name = "paras"
main = "dist/server/server.js"
compatibility_date = "2025-06-04"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "dist/client"

[[d1_databases]]
binding = "DB"
database_name = "punjab-rentals-db"
database_id = "b3c490bc-f8f5-4962-8055-f51ee6514b96"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "punjab-rentals-files"

[vars]
ENVIRONMENT = "production"
